services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - 3313:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql